### ISSUE TITLE
If using Altera USB Blaster do we still populate:- C4, R4 - R8, Q3 ?

### ISSUE THREAD

**Issue by Workz777** [borti4938/n64adv2_fw#1]
Hi, 

If we are using an Altera USB Blaster to flash the FPGA, do we still need to populate:- C4, R4, R5, R6, R7, R8 and Q3?

I saw on one of the installation photos the N64 Adv2 board didn't have the FPGA Programmer2 SMD-Module installed, and also didn't have the USB micro vertical port installed, but it did seem to have C4, R4 - R8, Q3 populated, so i wasn't sure.

Another question, when flashing the FPGA with the N64 console powered on, can the FPGA be flashed with the (Full) Flex PCB completely installed, or when it's just soldered / connected to the 3.3V, 5V and GND points on the N64 board?

Many thanks & kindest regards.

**Comment by borti4938** [comment]
Hello,

components C4, R4 to R8 and Q3 (as well as the micro USB port X5) are not needed if you do not use an onboard programmer module. I just usually populate C4, R4 to R8 and Q3 just in case I want to use an onboard programmer later on. In this case I (or someone else who has this board) just have to source USB port and programmer module.

For flashing the FPGA you need to power the 3.3V rail. This can be either done from external using the 3.3V and GND pads connected to a power supply. Or you simply install the board into an N64 and power the N64.
Side note: if you flash the board uninstalled I also recommend powering the 5V rail, which powers the HDMI transmitter. Just to be sure...

BR

**Comment by Workz777** [comment]
Thank-you Borti for the information, it's most appreciated.
